apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test
  namespace: ci-test
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: citest
    spec:
      containers:
      - name: citest
        image: nima3141/att1:latest
        command: ["/bin/echo", "hello"]
        
      
