apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test
  namespace: ci-test
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: citest
    spec:
      containers:
      - name: citest
        image: 216734445993.dkr.ecr.eu-central-1.amazonaws.com/r3pi-vi:latest
        
      
